version: '3.8'

services:

  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: prediction
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
    ports:
      - "5433:5432"


