version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: prediction
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
    ports:
      - "5432:5432"


  prediction:
    build:
      context: ./prediction
    container_name: prediction
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY
      - TIME_ZONE
      - DEBUG
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    env_file:
      - .env.docker
